language: python
os: linux
sudo: required
dist: xenial

python:
    - 3.6
notifications:
    email: false

services:
    - mysql

before_install:
    - pip install black
    - pip install future
    - pip install pytest
    -
install:
    - pip install .

before_script:
    - mysql -e "CREATE DATABASE test;"

script:
    # Run black on all .py files in all subfolders
    - black --check .

    # Set PYTHONPATH so that relative imports in click script work when pytest imports that
    - PYTHONPATH=. pytest
